// Everything on the "Show Me What You Know About Where" list.
// pt    = [longitude, latitude] of the point shown on the map.
// also  = other ways to write it that count: abbreviations and alternative names. Dropping "Lake", "River",
//         "Island", "Great" and so on is handled in app.js and does not need listing here.
// shape = the map feature to light up: province code, country id, lake name or river name.
// snap  = move the point onto the nearest bit of the drawn river.

// label = optional different name to print on the map.
// pool  = where multiple-choice wrong answers come from when a group is too small to fill four options.

const CATS = [
  { id: 'province', section: 'Places', label: 'Provinces & territories', noun: 'province or territory', ask: 'Which province or territory is this?', pool: 'province' },
  { id: 'capital',  section: 'Places', label: 'Capital cities',          noun: 'capital city', ask: 'Which capital city is this?', pool: 'cities' },
  { id: 'city',     section: 'Places', label: 'Other cities',            noun: 'city', ask: 'Which city is this?', pool: 'cities' },
  { id: 'country',  section: 'Places', label: 'Foreign countries',       noun: 'country', ask: 'Which country is this?', pool: 'country' },
  { id: 'island',   section: 'Places', label: 'Islands',                 noun: 'island', ask: 'Which island is this?', pool: 'island' },
  { id: 'ocean',    section: 'Water',  label: 'Oceans',                  noun: 'ocean', ask: 'Which ocean is this?', pool: 'salt' },
  { id: 'lake',     section: 'Water',  label: 'Lakes',                   noun: 'lake', ask: 'Which lake is this?', pool: 'lake' },
  { id: 'sea',      section: 'Water',  label: 'Seas',                    noun: 'sea', ask: 'Which sea is this?', pool: 'salt' },
  { id: 'bay',      section: 'Water',  label: 'Bays & gulfs',            noun: 'bay or gulf', ask: 'Which bay or gulf is this?', pool: 'salt' },
  { id: 'strait',   section: 'Water',  label: 'Straits',                 noun: 'strait', ask: 'Which strait is this?', pool: 'salt' },
  { id: 'river',    section: 'Water',  label: 'Rivers',                  noun: 'river', ask: 'Which river is this?', pool: 'river' },
];

const ITEMS = [
  // ── Provinces & territories ──
  { id: 'bc', cat: 'province', name: 'British Columbia', pt: [-124.5, 54.5], shape: 'CA-BC',
    also: ['bc'],
    hint: 'Westernmost province, on the Pacific coast.' },
  { id: 'ab', cat: 'province', name: 'Alberta', pt: [-114.5, 55.0], shape: 'CA-AB',
    also: ['ab', 'alta'],
    hint: 'Between British Columbia and Saskatchewan.' },
  { id: 'sk', cat: 'province', name: 'Saskatchewan', pt: [-106.0, 55.0], shape: 'CA-SK',
    also: ['sk', 'sask'],
    hint: 'Prairie province between Alberta and Manitoba. No coastline.' },
  { id: 'mb', cat: 'province', name: 'Manitoba', pt: [-97.5, 55.5], shape: 'CA-MB',
    also: ['mb', 'man'],
    hint: 'Easternmost Prairie province. Its north-east edge touches Hudson Bay.' },
  { id: 'on', cat: 'province', name: 'Ontario', pt: [-86.0, 50.5], shape: 'CA-ON',
    also: ['on', 'ont'],
    hint: 'North of the Great Lakes, south of Hudson Bay.' },
  { id: 'qc', cat: 'province', name: 'Quebec', pt: [-72.5, 52.5], shape: 'CA-QC',
    also: ['qc', 'que', 'pq'],
    hint: 'Largest province, east of Ontario.' },
  { id: 'nb', cat: 'province', name: 'New Brunswick', pt: [-66.4, 46.7], shape: 'CA-NB',
    also: ['nb'],
    hint: 'Borders Quebec and the U.S. state of Maine. West of Nova Scotia.' },
  { id: 'ns', cat: 'province', name: 'Nova Scotia', pt: [-62.9, 45.3], shape: 'CA-NS',
    also: ['ns'],
    hint: 'The peninsula east of New Brunswick, sticking out into the Atlantic.' },
  { id: 'pe', cat: 'province', name: 'Prince Edward Island', pt: [-63.9, 46.55], shape: 'CA-PE',
    also: ['pei', 'pe'],
    hint: 'Smallest province. The island in the Gulf of St. Lawrence.' },
  { id: 'nl', cat: 'province', name: 'Newfoundland and Labrador', pt: [-61.8, 53.6], shape: 'CA-NL',
    also: ['newfoundland labrador', 'labrador and newfoundland', 'nl', 'nfld', 'newfoundland', 'labrador'],
    hint: 'Two parts: the island of Newfoundland, and Labrador on the mainland beside Quebec.' },
  { id: 'yt', cat: 'province', name: 'Yukon', pt: [-136.0, 63.5], shape: 'CA-YT',
    also: ['yukon territory', 'the yukon', 'yt', 'yk'],
    hint: 'Westernmost territory, beside Alaska.' },
  { id: 'nt', cat: 'province', name: 'Northwest Territories', pt: [-118.0, 63.8], shape: 'CA-NT',
    also: ['nt', 'nwt'],
    hint: 'The middle territory, between Yukon and Nunavut.' },
  { id: 'nu', cat: 'province', name: 'Nunavut', pt: [-96.0, 65.0], shape: 'CA-NU',
    also: ['nu'],
    hint: 'Largest and easternmost territory. Includes most of the Arctic islands.' },

  // ── Capital cities ──
  { id: 'victoria', cat: 'capital', name: 'Victoria', pt: [-123.37, 48.43],
    hint: 'Capital of British Columbia. On the southern tip of Vancouver Island.' },
  { id: 'edmonton', cat: 'capital', name: 'Edmonton', pt: [-113.49, 53.55],
    hint: 'Capital of Alberta. Middle of the province, north of Calgary.' },
  { id: 'regina', cat: 'capital', name: 'Regina', pt: [-104.62, 50.45],
    hint: 'Capital of Saskatchewan. In the south, south-east of Saskatoon.' },
  { id: 'winnipeg', cat: 'capital', name: 'Winnipeg', pt: [-97.14, 49.90],
    hint: 'Capital of Manitoba. In the south, just below Lake Winnipeg.' },
  { id: 'toronto', cat: 'capital', name: 'Toronto', pt: [-79.38, 43.65],
    hint: 'Capital of Ontario. On the north-west shore of Lake Ontario.' },
  { id: 'quebec-city', cat: 'capital', name: 'Quebec City', pt: [-71.21, 46.81],
    also: ['ville de quebec'],
    hint: 'Capital of Quebec. On the St. Lawrence River, north-east of Montreal.' },
  { id: 'fredericton', cat: 'capital', name: 'Fredericton', pt: [-66.64, 45.96],
    hint: 'Capital of New Brunswick. Inland, in the southern half of the province.' },
  { id: 'halifax', cat: 'capital', name: 'Halifax', pt: [-63.57, 44.65],
    hint: 'Capital of Nova Scotia. On the Atlantic coast.' },
  { id: 'charlottetown', cat: 'capital', name: 'Charlottetown', pt: [-63.13, 46.24],
    hint: 'Capital of Prince Edward Island.' },
  { id: 'st-johns', cat: 'capital', name: "St. John's", pt: [-52.71, 47.56],
    hint: 'Capital of Newfoundland and Labrador. On the far eastern tip of Newfoundland.' },
  { id: 'whitehorse', cat: 'capital', name: 'Whitehorse', pt: [-135.05, 60.72],
    hint: 'Capital of Yukon. In the south of the territory.' },
  { id: 'yellowknife', cat: 'capital', name: 'Yellowknife', pt: [-114.37, 62.45],
    hint: 'Capital of the Northwest Territories. On the north shore of Great Slave Lake.' },
  { id: 'iqaluit', cat: 'capital', name: 'Iqaluit', pt: [-68.52, 63.75],
    hint: 'Capital of Nunavut. On the south-east of Baffin Island.' },
  { id: 'ottawa', cat: 'capital', name: 'Ottawa', pt: [-75.70, 45.42],
    hint: "The nation's capital. In Ontario, on the Ottawa River at the Quebec border." },

  // ── Other cities ──
  { id: 'vancouver', cat: 'city', name: 'Vancouver', pt: [-123.12, 49.28],
    also: ['vancouver british columbia', 'vancouver bc'],
    hint: 'British Columbia. On the mainland coast, across the water from Vancouver Island.' },
  { id: 'thunder-bay', cat: 'city', name: 'Thunder Bay', pt: [-89.25, 48.38],
    also: ['thunder bay ontario'],
    hint: 'Ontario. On the north-west shore of Lake Superior.' },
  { id: 'montreal', cat: 'city', name: 'Montreal', pt: [-73.57, 45.50],
    also: ['montreal quebec'],
    hint: 'Quebec. On the St. Lawrence River, south-west of Quebec City.' },
  { id: 'calgary', cat: 'city', name: 'Calgary', pt: [-114.07, 51.05],
    also: ['calgary alberta'],
    hint: 'Alberta. In the south, below Edmonton.' },
  { id: 'saskatoon', cat: 'city', name: 'Saskatoon', pt: [-106.67, 52.13],
    also: ['saskatoon saskatchewan'],
    hint: 'Saskatchewan. In the southern half, north-west of Regina.' },

  // ── Foreign countries ──
  { id: 'usa', cat: 'country', name: 'United States of America', pt: [-101.0, 45.2], shape: '840',
    also: ['usa', 'united states', 'us', 'america', 'the united states', 'the united states of america', 'states', 'united states america'],
    hint: 'The country south of Canada.' },
  { id: 'usa-alaska', cat: 'country', name: 'United States of America', label: 'U.S.A. (Alaska)', pt: [-152.0, 64.5], shape: '840',
    also: ['usa', 'united states', 'us', 'america', 'the united states', 'the united states of america', 'usa alaska', 'alaska usa', 'united states of america alaska', 'united states alaska', 'states', 'alaska'],
    hint: 'This part is Alaska, a U.S. state west of Yukon.' },
  { id: 'russia', cat: 'country', name: 'Russia', pt: [-172.5, 65.9], shape: '643',
    also: ['russian federation'],
    hint: 'Across the Bering Strait from Alaska, in the top-left corner of the map.' },
  { id: 'greenland', cat: 'country', name: 'Denmark (Greenland)', pt: [-44.0, 70.0], shape: '304',
    also: ['greenland', 'denmark', 'greenland denmark'],
    hint: 'The huge island north-east of Canada. Greenland belongs to Denmark.' },
  { id: 'iceland', cat: 'country', name: 'Iceland', pt: [-18.5, 65.0], shape: '352',
    hint: 'Island country east of Greenland.' },
  { id: 'spm', cat: 'country', name: 'France (St. Pierre and Miquelon)', pt: [-56.33, 46.94], shape: '666',
    also: ['st pierre and miquelon', 'france', 'st pierre and miquelon france', 'st pierre et miquelon', 'st pierre miquelon', 'france st pierre et miquelon', 'st pierre', 'spm'],
    hint: 'Tiny French islands just off the south coast of Newfoundland.' },

  // ── Islands ──
  { id: 'baffin', cat: 'island', name: 'Baffin Island', pt: [-71.5, 68.5],
    also: ['baffin'],
    hint: "Arctic. Canada's largest island, in Nunavut. Iqaluit is on it." },
  { id: 'ellesmere', cat: 'island', name: 'Ellesmere Island', pt: [-78.0, 80.0],
    also: ['ellesmere'],
    hint: 'Arctic. The northernmost island, right beside Greenland.' },
  { id: 'victoria-island', cat: 'island', name: 'Victoria Island', pt: [-110.0, 70.8],
    hint: 'Arctic. Split between Nunavut and the Northwest Territories, east of Banks Island.' },
  { id: 'banks', cat: 'island', name: 'Banks Island', pt: [-121.5, 73.0],
    also: ['banks'],
    hint: 'Arctic. The westernmost big island, in the Northwest Territories.' },
  { id: 'vancouver-island', cat: 'island', name: 'Vancouver Island', pt: [-125.5, 49.6],
    hint: "West coast. The large island off B.C.'s south-west corner. Victoria is on it." },
  { id: 'haida-gwaii', cat: 'island', name: 'Haida Gwaii', pt: [-132.3, 53.6],
    also: ['queen charlotte islands', 'haida gwaii islands'],
    hint: "West coast. The island group off B.C.'s north coast." },
  { id: 'cape-breton', cat: 'island', name: 'Cape Breton Island', pt: [-60.75, 46.5],
    also: ['cape breton'],
    hint: 'East coast. The north-east end of Nova Scotia.' },
  { id: 'manitoulin', cat: 'island', name: 'Manitoulin Island', pt: [-82.3, 45.75],
    also: ['manitoulin'],
    hint: 'Ontario. In the north of Lake Huron, west of Georgian Bay.' },

  // ── Oceans ──
  { id: 'arctic', cat: 'ocean', name: 'Arctic Ocean', pt: [-125.0, 80.0],
    also: ['arctic'],
    hint: 'North of Canada.' },
  { id: 'pacific', cat: 'ocean', name: 'Pacific Ocean', pt: [-134.0, 48.5],
    also: ['pacific'],
    hint: 'West of British Columbia.' },
  { id: 'atlantic', cat: 'ocean', name: 'Atlantic Ocean', pt: [-55.0, 43.5],
    also: ['atlantic'],
    hint: 'East of the Maritime provinces and Newfoundland.' },

  // ── Lakes ──
  { id: 'great-bear', cat: 'lake', name: 'Great Bear Lake', pt: [-120.8, 66.0], shape: 'Great Bear Lake',
    also: ['great bear'],
    hint: 'Northwest Territories. The more northern of the two big lakes.' },
  { id: 'great-slave', cat: 'lake', name: 'Great Slave Lake', pt: [-114.0, 61.4], shape: 'Great Slave Lake',
    also: ['great slave'],
    hint: 'Northwest Territories. The southern big lake. Yellowknife sits on its north shore.' },
  { id: 'athabasca', cat: 'lake', name: 'Lake Athabasca', pt: [-109.36, 59.35], shape: 'Lake Athabasca',
    also: ['athabasca', 'athabasca lake'],
    hint: 'Crosses the Alberta–Saskatchewan border in the north.' },
  { id: 'lake-winnipeg', cat: 'lake', name: 'Lake Winnipeg', pt: [-97.9, 53.0], shape: 'Lake Winnipeg',
    also: ['winnipeg lake'],
    hint: 'Manitoba. The long north–south lake above the city of Winnipeg.' },
  { id: 'superior', cat: 'lake', name: 'Lake Superior', pt: [-87.5, 47.7], shape: 'Lake Superior',
    also: ['superior'],
    hint: 'Great Lake. The biggest one, furthest north and west.' },
  { id: 'huron', cat: 'lake', name: 'Lake Huron', pt: [-82.4, 44.7], shape: 'Lake Huron',
    also: ['huron'],
    hint: 'Great Lake. East of Lake Michigan. Georgian Bay is its eastern arm.' },
  { id: 'michigan', cat: 'lake', name: 'Lake Michigan', pt: [-87.0, 43.8], shape: 'Lake Michigan',
    also: ['michigan'],
    hint: 'Great Lake. The only one entirely inside the U.S.A. It hangs straight down.' },
  { id: 'erie', cat: 'lake', name: 'Lake Erie', pt: [-81.2, 42.2], shape: 'Lake Erie',
    also: ['erie'],
    hint: 'Great Lake. The southernmost one, under south-western Ontario.' },
  { id: 'lake-ontario', cat: 'lake', name: 'Lake Ontario', pt: [-77.8, 43.65], shape: 'Lake Ontario',
    hint: 'Great Lake. The smallest and furthest east. Toronto is on its shore.' },

  // ── Seas ──
  { id: 'beaufort', cat: 'sea', name: 'Beaufort Sea', pt: [-138.0, 72.3],
    also: ['beaufort'],
    hint: 'North of Yukon, Alaska and the western Northwest Territories.' },
  { id: 'labrador-sea', cat: 'sea', name: 'Labrador Sea', pt: [-55.0, 58.0],
    hint: 'Between Labrador and Greenland.' },

  // ── Bays & gulfs ──
  { id: 'hudson-bay', cat: 'bay', name: 'Hudson Bay', pt: [-86.0, 60.0],
    hint: 'The giant bay in the middle of Canada, touching Nunavut, Manitoba, Ontario and Quebec.' },
  { id: 'james-bay', cat: 'bay', name: 'James Bay', pt: [-80.5, 53.3],
    also: ['james'],
    hint: 'The small bay hanging off the bottom of Hudson Bay, between Ontario and Quebec.' },
  { id: 'georgian-bay', cat: 'bay', name: 'Georgian Bay', pt: [-80.9, 45.2],
    also: ['georgian'],
    hint: 'Ontario. The big eastern arm of Lake Huron.' },
  { id: 'ungava-bay', cat: 'bay', name: 'Ungava Bay', pt: [-67.5, 59.5],
    also: ['ungava'],
    hint: 'Quebec. The notch in the top of the province, opening onto Hudson Strait.' },
  { id: 'fundy', cat: 'bay', name: 'Bay of Fundy', pt: [-65.9, 44.95],
    also: ['fundy', 'fundy bay'],
    hint: 'Between New Brunswick and Nova Scotia.' },
  { id: 'gulf-st-lawrence', cat: 'bay', name: 'Gulf of St. Lawrence', pt: [-60.5, 48.3],
    also: ['st lawrence gulf', 'gulf of the st lawrence'],
    hint: 'Where the St. Lawrence River meets the Atlantic, between Quebec, Newfoundland and the Maritimes.' },
  { id: 'gulf-alaska', cat: 'bay', name: 'Gulf of Alaska', pt: [-146.0, 57.5],
    also: ['alaska gulf'],
    hint: 'The curve of the Pacific below southern Alaska.' },

  // ── Straits ──
  { id: 'hudson-strait', cat: 'strait', name: 'Hudson Strait', pt: [-71.0, 62.2],
    hint: 'Joins Hudson Bay to the Labrador Sea, between Baffin Island and northern Quebec.' },
  { id: 'bering', cat: 'strait', name: 'Bering Strait', pt: [-168.9, 65.8],
    also: ['bering'],
    hint: 'The narrow gap between Alaska and Russia.' },
  { id: 'davis', cat: 'strait', name: 'Davis Strait', pt: [-57.5, 66.5],
    also: ['davis'],
    hint: 'Between Baffin Island and Greenland.' },

  // ── Rivers ──
  { id: 'fraser', cat: 'river', name: 'Fraser River', pt: [-122.4, 52.6], shape: 'Fraser', snap: true,
    also: ['fraser'],
    hint: 'British Columbia. Flows south, reaching the Pacific at Vancouver.' },
  { id: 'mackenzie', cat: 'river', name: 'Mackenzie River', pt: [-125.5, 64.9], shape: 'Mackenzie', snap: true,
    also: ['mackenzie'],
    hint: 'Northwest Territories. Flows north-west from Great Slave Lake to the Beaufort Sea.' },
  { id: 'nelson', cat: 'river', name: 'Nelson River', pt: [-95.5, 56.2], shape: 'Nelson', snap: true,
    also: ['nelson'],
    hint: 'Manitoba. Flows from the top of Lake Winnipeg north-east into Hudson Bay.' },
  { id: 'churchill', cat: 'river', name: 'Churchill River', pt: [-95.5, 58.2], shape: 'Churchill', snap: true,
    also: ['churchill'],
    hint: 'Manitoba. North of the Nelson. Reaches Hudson Bay at the town of Churchill.' },
  { id: 'ottawa-river', cat: 'river', name: 'Ottawa River', pt: [-77.5, 45.95], shape: 'Ottawa', snap: true,
    hint: 'Forms much of the Ontario–Quebec border and joins the St. Lawrence near Montreal.' },
  { id: 'st-lawrence', cat: 'river', name: 'St. Lawrence River', pt: [-72.5, 46.3], shape: 'St. Lawrence', snap: true,
    also: ['st lawrence'],
    hint: 'Flows north-east from Lake Ontario past Montreal and Quebec City to the Gulf of St. Lawrence.' },
];
